### ISSUE TITLE
Knowledge - Ingestion of files fails with `fitz: cannot open memory` error.  This also results in blocking ingestion of other files.

### ISSUE THREAD

**Issue by sangee2004** [obot-platform/obot#150]
**Steps to reproduce the problem:**
1. Create an agent with knowledge from website - `cry.org`

Following error is seen for one of the files:

<img width="651" alt="Screenshot 2024-10-09 at 2 41 48 PM" src="https://github.com/user-attachments/assets/bed7c970-ab35-41e0-a857-50cb8cec88dc">

When i open this pdf file , it takes me to `https://www.cry.org/404page/` which is already one of the scraped files.

After which ingestion of other files does not continue:

<img width="715" alt="Screenshot 2024-10-09 at 2 51 49 PM" src="https://github.com/user-attachments/assets/1d84c13f-d217-4cf6-b1b4-93320107fa4d">

Stack trace calls - [calls (28).json](https://github.com/user-attachments/files/17319188/calls.28.json)

**Comment by sangee2004** [comment]
Seeing this issue when ingesting`coral.org`

This url shows the problem - http://www.salinitymanagement.org/Salinity%20Brochure.pdf

<img width="1078" alt="Screenshot 2024-11-22 at 11 44 38 AM" src="https://github.com/user-attachments/assets/349da219-eec1-491e-8f10-bc93e1d767fe">

**Comment by iwilltry42** [comment]
@sangee2004 (cc @StrongMonkey ) - this is again a `301` leading from http://www.salinitymanagement.org/Salinity%20Brochure.pdf  to https://www.sammenlignforbrukslån.net/
