### ISSUE TITLE
Provide a way to interrupt a response when it is being streamed.

### ISSUE THREAD

**Issue by sangee2004** [obot-platform/obot#358]
Currently there is no way to interrupt a response when it is being streamed.

**Comment by cjellick** [comment]
API now exists: `threads/{id}/abort`

@ivyjeong13 - im going to assign this to you so that you can get some exposure to the chat functionality

**Comment by cjellick** [comment]
functionality is already in the consumption ui, so this just needs done in admin ui

**Comment by sangee2004** [comment]
When testing with latest version we are provided with ability to interrupt chat responses.
