### ISSUE TITLE
Knowledge - UI - Name of the scraped file in `Status` uses a very small width resulting in wrapping the text leading to overlap with other fields.

### ISSUE THREAD

**Issue by sangee2004** [obot-platform/obot#464]
Steps to reproduce the problem:
1. Create an agent with knowledge from website
2. Notice that name of the scraped file in `Status` field uses a very small width resulting in wrapping the text leading to overlap with other fields.

In this case, we would have easily accommodated the file name in one line
<img width="1066" alt="Screenshot 2024-11-06 at 1 22 36 PM" src="https://github.com/user-attachments/assets/562cc76a-c1cd-496e-8db5-19738911ff28">

In this case, the file name overlaps to Sync status field.

<img width="649" alt="Screenshot 2024-11-06 at 1 24 21 PM" src="https://github.com/user-attachments/assets/b8d3aed2-2e7f-4892-95f9-dac2e074f5dc">

**Comment by cjellick** [comment]
@sangee2004 - in situations like this where the original issue is addressed, it becomes a burden for me and the developer to track the history of these. For example, the title and steps to reproduce for this issue now do not reflect the bug at all.

When the original issue is addressed, but you find a new related issues, can you close the orignal and open a new issue that accurately reflects the bug you want addressed?

**Comment by sangee2004** [comment]
Logged -https://github.com/otto8-ai/otto8/issues/750 to track the issue from https://github.com/otto8-ai/otto8/issues/464#issuecomment-2471524964. 

Closing this issue.
