### ISSUE TITLE
Provide userid information for admin create threads in thread list view.

### ISSUE THREAD

**Issue by sangee2004** [obot-platform/obot#530]
Currently there is no way to know who is the owner of the thread from the thread list view

<img width="1168" alt="Screenshot 2024-11-11 at 10 08 22 AM" src="https://github.com/user-attachments/assets/8ce35792-acc9-4ecb-a728-8fb957c53c06">

We should be able to provide userid information in thread list view.

**Comment by cjellick** [comment]
We do show user now, but only for threads created in the user UI. Threads created via admin UI do no show the user. I'd like it to.

**Comment by cjellick** [comment]
im just going to close this and create a fresh issue for the admin thread bit
