### ISSUE TITLE
[RFE] Azure managed identity support

### ISSUE THREAD

**Issue by thoraxe** [obot-platform/obot#601]
Currently Otto8 only supports API keys for Azure OpenAI. API key functionality is extremely limited with Azure OpenAI and Microsoft's intention is for users to use more advanced auth mechanisms like app registrations and Entra IDs/workload identities for "proper" authentication.

It would be good if Otto8 could support using other credential mechanisms for authenticating to Azure OpenAI. At a minimum, app registration credentials would be nice (app id, tenant, password).

**Comment by cjellick** [comment]
thanks for the request!

**Comment by cjellick** [comment]
Can you elaborate on "extremely limited"? I'd like to better understand what the tangible shortcomings are so that when we implement this, we know what to look for.

**Comment by thoraxe** [comment]
Azure OpenAI provides no ability for you to "manage" API keys. You get 2 keys when you create an Azure OpenAI instance and they cannot be individually rotated. You have no ability to create additional API keys like you can with OpenAI proper. These concepts simply don't exist.

Most commercial users of Azure OpenAI will be using something like App Registration with certificate creation or things like Entra ID managed identities to access Azure OpenAI.

Take a look at https://learn.microsoft.com/en-us/azure/developer/go/azure-sdk-authentication?tabs=bash as a potential starting point.

**Comment by thedadams** [comment]
This has been addressed in the v0.4.0 release of Obot.
