### ISSUE TITLE
Credentials relating to env do not get cleared when environment variable is deleted(or edited) for a workflow.

### ISSUE THREAD

**Issue by sangee2004** [obot-platform/obot#749]
**Steps to reproduce the problem:**
**Scenario 1:**

1. Register a  tool with url - `github.com/sangee2004/gptscript/tools/testenv` ( simple tool that print paramter and environment variable)
2. Created a workflow with env variable `MY_ENV`, parameter `PROMPT` and add the tool from step 1.
3. Add a step with `print`
4. Use `Authenticate` and enter value for `MY_ENV` when prompted for it.
5. Use `Run workflow` to run the workflow.
6. Delete the env variable `MY_ENV`
7. Run `Authenticate` ( You dont have to do this step as well). 
8. Use `Run workflow` to run the workflow again.
Tool call will fail with needing environment variable which is as expected.
9. Add  env variable `MY_ENV` back.
10.  Use `Authenticate` 
Notice that we are not prompted to enter `MY_ENV` variable ( the credential created from step4 is still present) and presented with `DONE`.
11. Use `Run workflow` to run the workflow.
Tool will get the value for `MY_ENV` as the value set in step 4.

**Expected Behavior:**
Deleting environment variable in step 6 , should have deleted the related credential.
`Authenticate`  in step 10 should prompt the user to enter  `MY_ENV` variable.

**Scenario 2:**
1. Created a workflow with env variable `MY_ENV`
2. `Authenticate`

credential relating to env gets created as expected.
```
w16fmf6::MY_ENV       MY_ENV       never
```

3. Edit the `MY_ENV` to `MY_ENV_mod`
4. `Authenticate`

This results in new credential relating to `MY_ENV_mod` getting created.
credential relating to `MY_ENV` continues to remain.
```
w16fmf6::MY_ENV       MY_ENV       never
w16fmf6::MY_ENV_mod   MY_ENV_mod   never
```

**Expected Behavior:**
credential relating to `MY_ENV` should get deleted.

**Comment by cjellick** [comment]
The entire flow for setting/getting env vars is going to be updated.

**Comment by cjellick** [comment]
im just going to close this since the new flow is going to be so different
