### ISSUE TITLE
Knowledge - Scrapped file name shifts  left or right (depending on the file name size) as they get displayed in Sync status field.

### ISSUE THREAD

**Issue by sangee2004** [obot-platform/obot#750]
**Steps to reproduce the problem:**
1.  Create an agent with knowledge files from `acorn.io`

Notice that when sync is in progress , scrapped file name shifts  left or right (depending on the file name size) as they get displayed in Sync status field.

https://github.com/user-attachments/assets/61c6665b-cc27-4031-ba44-e589121fda98

**Expected Behavior:**
Ideally text relating to scrapped file should not shift left or right (depending on the file name size). This happens because of the text being right aligned (like all other fields).  Would it be better to make this text left aligned ?

**Comment by StrongMonkey** [comment]
Yes, text are all aligned to the right to match how other fields get displayed.

**Comment by iwilltry42** [comment]
@cjellick this seems to be a pretty subtle design decision - what do you want to do here?
cc @ivyjeong13 @ryanhopperlowe

**Comment by cjellick** [comment]
Skip it Thorsten. Can have i ui dev look at it.

In general you don't need to spend much time on outlet UI issues

**Comment by ryanhopperlowe** [comment]
Personally, I think that having it right aligned makes the most sense here. @cjellick what do you want to do?

**Comment by ryanhopperlowe** [comment]
Closing this issue.

@ivyjeong13 Feel free to weigh in here if you disagree.
