### ISSUE TITLE
Knowledge - Refactor website-cleaner tool

### ISSUE THREAD

**Issue by iwilltry42** [obot-platform/obot#753]
Changelist:

- reduce scraper (colly) to only scrape and save html (i.e. remove markdown conversion)
- make the website-cleaner a code-based tool
	- use the workspace api to fetch the HTML
	- clean the HTML programatically (like in that PR I have up right now)
	- convert to markdown (I don't actually know if the LLM will be better at cleaning HTML or Markdown)
	- use the gptscript sdk to send the markdown to OpenAI for cleaning - with retries based on error text
	- use the workspace api to save the resulting markdown
- in otto8 remove the size limitation and pass the workspace filepath to the new website-cleaner tool

**Comment by sangee2004** [comment]
Tested Ingestion of few websites with these change.

I am seeing few ingestion failures relating to - `failed to clean website content: run exceeded maximum time of 10m0s` which is tracked in https://github.com/obot-platform/obot/issues/926.

Closing this issue.
