### ISSUE TITLE
Knowledge -"Add folder to knowledge" gets blocked after approving few files and leaving lots of files in the folder in unapproved state.

### ISSUE THREAD

**Issue by sangee2004** [obot-platform/obot#822]
I had created an agent with knowledge from onedrive link to `corp docs` which has ~600+ files.
Once sync is completed, used "Add folder to knowledge`  option to include and ingest all files in the folder.

Out of the 671 synced files, only 508 files were included. File ingestion for some of the included files succeeded.

I did not see any progress made after this state for a long time.

<img width="1077" alt="Screenshot 2024-12-07 at 8 40 12 AM" src="https://github.com/user-attachments/assets/1895dca9-1a6a-453c-9058-520452e29304">

Had to do `Add folder to knowledge` option again  that resulted in rest of the files to get  included and ingestion of all files completed.

**Note** 
1. When I use "Add folder to knowledge"  option, I always see ingestion starts only after all the files have been approved. 

Does this mean, in this case there was some issue encountered during approval of files which resulted in file approval to halt and ingestion process to start?

2. Tried to see if I was able to reproduce the approval process to get halted by closing the knowledge page after `Add folder to knowledge"` was started and when file approval was still in progress. This did not halt the file approval process. When I launched the knowledge page again , i was able to see the file approval process continue for other files in the folder.

**Comment by StrongMonkey** [comment]
This should be fixed. When you add a folder in UI, there are two actions:
1. Adding the folder path to approve prefix list.
2. Approving individual files one by one.

Right now we add folder path to approve prefix list first and then start approving individual files. So if the second step is interrupted the first step will guarantee that the rest of the file will be reconciled to be approved in the backend eventually.

**Comment by sangee2004** [comment]
I have not been able to reproduce this issue when testing with latest build. In the last few attempts with ingesting corp docs, i have been able to approve and ingest all files when using "Add folder to knowledge" option.
Closing this issue.

**Comment by sangee2004** [comment]
@StrongMonkey I am seeing this issue reproduce in test env right now - https://test.acornlabs.com/admin/agents/a17r6vl

**Comment by sangee2004** [comment]
Saw this issue happen again today - https://test.acornlabs.com/admin/agents/a14hflh

**Comment by sangee2004** [comment]
This issue is not seen anymore when testing with latest builds.
