### ISSUE TITLE
Support anthropic via bedrock as a model provider

### ISSUE THREAD

**Issue by iwilltry42** [obot-platform/obot#832]
- Move the bedrock

**Comment by cjellick** [comment]
Im going to break this into two separate issues - one for gemini, one for anthropic via bedrock

**Comment by cjellick** [comment]
Reason that streaming and non-streaming switch needs to work properly:


> There is a call in knowledge (I believe it was the website cleaner) that explicitly makes a call to chat completion with streaming turned off.

**Comment by sangee2004** [comment]
Able to configure `Anthropic on AWS Bedrock provider` model provider and work with models from them.

Issues found when testing with this provider will be logged as separate issues

Issues found so far:

https://github.com/obot-platform/obot/issues/1003
https://github.com/obot-platform/obot/issues/1002
https://github.com/obot-platform/obot/issues/1001
https://github.com/obot-platform/obot/issues/998
