### ISSUE TITLE
Add JIRA Tool

### ISSUE THREAD

**Issue by billabongrob** [obot-platform/obot#867]
We would like to request the addition of a JIRA tool to the repository. This tool should enable users to interact with JIRA, including creating, updating, and querying issues.

**Proposed Features:**

Create JIRA Issue: Allow users to create new issues in JIRA.
Update JIRA Issue: Enable users to update existing issues in JIRA.
Query JIRA Issues: Provide functionality to search and retrieve issues from JIRA.
Add Comments to JIRA Issues: Allow users to add comments to existing JIRA issues.

**Benefits:**

Streamline project management by integrating JIRA with the existing toolset.
Improve productivity by allowing users to manage JIRA issues directly from the repository.
Enhance collaboration by providing a unified interface for issue tracking and management.

**Additional Information:**

The tool should support authentication with JIRA using similar OAUTH mechanisms in place today.
It should handle different JIRA projects and issue types.
The tool should provide clear error messages and handle exceptions gracefully.

Thank you for considering this feature request. We believe that adding a JIRA tool will greatly enhance the functionality of the repository and benefit all users.

**Comment by sangee2004** [comment]
Able to configure Atlassian Oauth App successfully following the instructions provided for the Oauth provider.

Created an agent with `jira` bundle and was able to do the following:

```
Create JIRA Issue: Allow users to create new issues in JIRA.
Update JIRA Issue: Enable users to update existing issues in JIRA.
Query JIRA Issues: Provide functionality to search and retrieve issues from JIRA.
Add Comments to JIRA Issues: Allow users to add comments to existing JIRA issues.

```

Was also able to use all other tools available in the bundle. I have not been able to test `list priorities` tool which i will be following up on.
