### ISSUE TITLE
Default OAuth apps to host Acorn

### ISSUE THREAD

**Issue by thedadams** [obot-platform/obot#905]
The Gateway currently hosts the default OAuth app configurations. The user can override those by creating OAuth apps in the admin UI.

In order to decommision Gateway, if that becomes desired, we need the default OAuth apps to be in Acorn.

**Comment by cjellick** [comment]
changing from enhancement to chore since this really doesn't add anything the user would notice. it's more of a maintenance or architecture thing.

**Comment by cjellick** [comment]
Actually, im going to close this and just make this a comment on the issue to decomission the gateway.
