### ISSUE TITLE
Knowledge - Knowledge tools gets called when we dont expect it to be called and it fails with `502 <Model.otto.otto8.ai \"text-embedding-3-large\" not found\` error.

### ISSUE THREAD

**Issue by sangee2004** [obot-platform/obot#931]
**Steps to reproduce the problem:**
1.  Create an agent with knowledge tool .
2.  Do not add any knowledge files.
3. Chat with agent.

Notice that knowledge tool gets called and fails 
<img width="1018" alt="Screenshot 2024-12-17 at 3 19 56 PM" src="https://github.com/user-attachments/assets/5008593a-a826-4320-aff1-5178099f2e28" />

Error seen in tool calls
<code>
            "content": "ERROR: got (exit status 1) while running tool, OUTPUT: 2024/12/17 23:15:22 INFO Retrieving sources for query query=\"site:github.com/obot-platform/obot most recent message\" datasets=[default]\n2024/12/17 23:15:22 WARN Request failed - Retryable error=\"#1/5: 502 <Model.otto.otto8.ai \\\"text-embedding-3-large\\\" not found\\n> (err: <nil>)\"\n2024/12/17 23:15:22 WARN Request failed - Retryable error=\"#2/5: 502 <Model.otto.otto8.ai \\\"text-embedding-3-large\\\" not found\\n> (err: <nil>)\"\n2024/12/17 23:15:23 WARN Request failed - Retryable error=\"#3/5: 502 <Model.otto.otto8.ai \\\"text-embedding-3-large\\\" not found\\n> (err: <nil>)\"\n2024/12/17 23:15:24 WARN Request failed - Retryable error=\"#4/5: 502 <Model.otto.otto8.ai \\\"text-embedding-3-large\\\" not found\\n> (err: <nil>)\"\n2024/12/17 23:15:26 WARN Request failed - Retryable error=\"#5/5: 502 <Model.otto.otto8.ai \\\"text-embedding-3-large\\\" not found\\n> (err: <nil>)\"\n2024/12/17 23:15:29 ERROR request retry limit exceeded or failed with non-retryable error(s) request=\"&{Method:POST URL:http://localhost:8080/api/llm-proxy/embeddings Proto:HTTP/1.1 ProtoMajor:1 ProtoMinor:1 Header:map[Authorization:[Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZ2VudElEIjoiYTFyaGR4dyIsIlJ1bklEIjoicjFod2o2diIsIlNjb3BlIjoiZGVmYXVsdCIsIlRocmVhZElEIjoidDFjOTc1OSIsIlVzZXJFbWFpbCI6IiIsIlVzZXJJRCI6IiIsIlVzZXJOYW1lIjoiIiwiV29ya2Zsb3dJRCI6IiIsIldvcmtmbG93U3RlcElEIjoiIn0.2o2HPnTEA-gZ-uHLTNvd5ivb71nAejffM9KlhJ7OXGw] Content-Type:[application/json]] Body:{Reader:} GetBody:0x862ff0 ContentLength:143 TransferEncoding:[] Close:false Host:localhost:8080 Form:map[] PostForm:map[] MultipartForm:<nil> Trailer:map[] RemoteAddr: RequestURI: TLS:<nil> Cancel:<nil> Response:<nil> Pattern: ctx:0x400060e000 pat:<nil> matches:[] otherValues:map[]}\"\n2024/12/17 23:15:29 failed to retrieve documents for query \"site:github.com/obot-platform/obot most recent message\" using retriever \"basic\": error sending request(s): retry limit (5) exceeded or failed with non-retryable error(s): #1/5: 502 <Model.otto.otto8.ai \"text-embedding-3-large\" not found\n> (err: <nil>); #2/5: 502 <Model.otto.otto8.ai \"text-embedding-3-large\" not found\n> (err: <nil>); #3/5: 502 <Model.otto.otto8.ai \"text-embedding-3-large\" not found\n> (err: <nil>); #4/5: 502 <Model.otto.otto8.ai \"text-embedding-3-large\" not found\n> (err: <nil>); #5/5: 502 <Model.otto.otto8.ai \"text-embedding-3-large\" not found\n> (err: <nil>)\n",
</code>

Debug call logs  - [calls (54).json](https://github.com/user-attachments/files/18172405/calls.54.json)

**Note** - I have seen this behavior when chatting with `obot` agent as well which also have the `knowledge` tool .

**Expected Behavior:**
1. We dont expect knowledge tool to be called in this case.
2. Even if it gets called , we should not be seeing `502 model not found` error.

**Comment by iwilltry42** [comment]
Apparently it is expected to be callable even if there's no data inside, but it's still up to the LLM to decide when to use it.
The second part of this is fixed :+1:

**Comment by sangee2004** [comment]
This issue is fixed when testing with latest builds

Knowledge tool call fails with following error message now.
```
      "err": null,
      "fullOutput": "2024/12/19 21:47:22 ERROR exiting with error error=\"no dataset specified for retrieval - probably there was nothing ingested yet\" fields=\"\"\n{\"error\": \"no dataset specified for retrieval - probably there was nothing ingested yet\"}\n",
      "output": "{\"error\": \"no dataset specified for retrieval - probably there was nothing ingested yet\"}\n"
```
