### ISSUE TITLE
Admin UI - Auto Add knowledge tool when uploading knowledge to an agent/workflow

### ISSUE THREAD

**Issue by ryanhopperlowe** [obot-platform/obot#933]
When knowledge is uploaded to an agent/workflow, the UI should automatically add the knowledge tool if it is not already present

Discussion for context:
https://acorn-io.slack.com/archives/C07P0EZR917/p1734463407097269

**Comment by sangee2004** [comment]
knowledge tool get adds auto added when knowledge files are added as local files/webdites/onedrivelink link/notion.
