### ISSUE TITLE
Use `webp` for generated images

### ISSUE THREAD

**Issue by njhale** [obot-platform/obot#936]
## Overview

Today, the `Generate Images` tool produces `png` files. We want it to produce `webp` instead.

## Motivation

The `webp` format is more compact and it's what ChatGPT produces when asked to generate an image.

## Design

- OpenAI's image generation API produces `png` images, so at minimum, the tool will need to convert them from `png` to `webp` before storing the image
- Some models may produce images in formats other than `png` -- e.g. `jpeg` -- so the more formats the tool can convert to `webp`, the better

**Comment by sangee2004** [comment]
Tested with latest version of tool - ` "github.com/otto8-ai/tools": "93d8f70e842634fac12e69a7d0f4b05461932348"`

1. Chat with `obot` and ask to generate an image.
2. Once the image is generated , ask to list all files

Image file relating to the generated image is stored as `.webp`
<img width="570" alt="Image" src="https://github.com/user-attachments/assets/5a106e65-f47d-46c3-95ce-2dd96a2d9685" />
