### ISSUE TITLE
Add support for analyzing `webp` images

### ISSUE THREAD

**Issue by njhale** [obot-platform/obot#937]
## Overview

The `Analyze Images` tool currently supports analyzing `png` and `jpeg` images. We want to add support for `webp` as well.

## Motivation

- The `Generate Images` tool will produce `webp` images once #936 is implemented, so the `Analyze Images` tool must be able to analyze `webp` images to continue support for "round-tripping" (i.e. analyzing generated images)
- `webp` is a ubiquitous image format and supporting it will 

## Design

OpenAI's Chat Completion API already supports `webp`, so the required changes should be trivial.

**Comment by sangee2004** [comment]
Able to analyze webp images when testing with latest tools.

<img width="612" alt="Image" src="https://github.com/user-attachments/assets/55552392-3a43-4244-8fd5-ed67744d4f5b" />
