### ISSUE TITLE
groq - When chatting with `obot` , tool calls unrelated to the chat gets called.

### ISSUE THREAD

**Issue by sangee2004** [obot-platform/obot#957]
**Steps to reproduce the problem:**

1. Configure groq  model provider and set `llama-3.1-8b-instant` model as default LLM alias.
<img width="831" alt="Screenshot 2024-12-18 at 12 29 53 PM" src="https://github.com/user-attachments/assets/c0242c39-066b-4a29-ba93-ab6168f7cab1" />

2. Chat with `obot` agent and ask for garden ideas

Notice that there are tool calls that get made to tools unrelated to chat and `workspace_read` , `workspace_write`, `workspace-copy` get called in a loop endlessly until i get rate limited eventually

<img width="484" alt="Screenshot 2024-12-18 at 12 33 23 PM" src="https://github.com/user-attachments/assets/de67b4f3-b7dd-4bbd-9f5b-c06e669df1b7" />

<img width="1132" alt="Screenshot 2024-12-18 at 12 38 15 PM" src="https://github.com/user-attachments/assets/f15371cb-1324-4099-a1b6-6ff9e100dda7" />

Debug logs - [calls (65).json](https://github.com/user-attachments/files/18188584/calls.65.json)

**Comment by sanjay920** [comment]
this seems to be a groq llama3.1 issue
