### ISSUE TITLE
Issues seen with listing tables in chat view.

### ISSUE THREAD

**Issue by sangee2004** [obot-platform/obot#966]
**Steps to reproduce the problem:**
**Scenario 1:**
1. Go to `http://localhost:8080/obot` to chat with obot agent.
2. Click on "Tables" to list tables when there are no tables.

Notice that table list is shown as "Loading.." for ever. 

<img width="1198" alt="Screenshot 2024-12-18 at 3 35 27 PM" src="https://github.com/user-attachments/assets/1ba9cd05-7716-444c-ad0e-580f3547ff7c" />

Using "Refresh" option does not get us out of this state.

**Scenario 2:**
3.  Chat with obot agent and Create a table with few rows.
4.  Click on "Tables" to list tables. 

Notice that no tables are listed. using "Refresh" option does not get us out of this state.

When the whole chat page is refreshed and then visiting "Tables" will list the table.

https://www.loom.com/share/422b32785d1d4826b3c040c796e48bf5?sid=9cadd218-e7f1-48e0-b24d-d7d0c1881668

**Comment by cjellick** [comment]
Don't combine bugs like this. The title is so generic. The scenarios could use more details as well. Like for the first scenario are you saying we never show any tables? If so, then the feature is completely non-functional. Is that the case?
