### ISSUE TITLE
Show interrupted chat message(and response) in thread view.

### ISSUE THREAD

**Issue by sangee2004** [obot-platform/obot#985]
**Steps to reproduce the problem:**
1. Create an agent and chat with the agent.
2. When message response is in progress , interrupt the chat message.
3. Have other conversations.

In this case, chat response for gardening ideas was interrupted

<img width="489" alt="Screenshot 2024-12-19 at 10 27 37 AM" src="https://github.com/user-attachments/assets/d41b84eb-8750-4581-b321-90ef7899cc89" />

5. Quit the chat view.
6. Revisit this thread.

Notice that the chat message (and response) that was interrupted ("gardening ideas" in my case) is not present in the thread view anymore.

<img width="501" alt="Screenshot 2024-12-19 at 10 28 01 AM" src="https://github.com/user-attachments/assets/b05d7e72-ea50-4aad-81d6-b1a979427ea9" />

Note - This issue is seen with both `admin-ui` and `user` ui.

**Comment by cjellick** [comment]
This is expected behavior. You interupted it, so it did not become part of the chat history
